"""Build shareable versions of Lizard Leap from game.py.

    python build.py html   ->  dist/LizardLeap.html  (plays in any browser, no Python needed)
                               docs/                 (GitHub Pages site, installable as a phone app)
    python build.py exe    ->  dist/LizardLeap.exe   (Windows app with the FastAPI server inside)
    python build.py        ->  both

game.py stays the one source to edit; re-run this after changing it.
Needs Pillow for the icons; the exe target also needs PyInstaller (python -m pip install pyinstaller).
"""
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).parent
DIST = HERE / "dist"
# PyInstaller's scratch files live outside the project: OneDrive locks files it's syncing,
# which makes PyInstaller's cleanup fail with "Access is denied".
WORK = Path(tempfile.gettempdir()) / "LizardLeap-build"


def build_html():
    from game import PAGE

    server_line = 'const SCORE_API = "/api/highscore";'
    if server_line not in PAGE:
        sys.exit(f"build.py: couldn't find `{server_line}` in game.py - did it get renamed?")
    page = PAGE.replace(server_line, 'const SCORE_API = "";   // standalone: best score saved in the browser')
    if PWA_MARKER not in page:
        sys.exit(f"build.py: couldn't find `{PWA_MARKER}` in game.py's <head>")

    # dist/LizardLeap.html is the single file to send people (a phone app needs a web address, so no PWA bits)
    write(DIST / "LizardLeap.html", page.replace(PWA_MARKER, ""))
    # docs/ is what GitHub Pages serves: the same page plus what phones need to install it as an app
    build_pwa(page)


def write(out: Path, text: str):
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    size = out.stat().st_size
    print(f"Built {out.relative_to(HERE)}" + (f" ({size // 1024} KB)" if size >= 1024 else ""))


# ---------- installable phone app (Progressive Web App) for GitHub Pages ----------
PWA_MARKER = "<!-- PWA -->"
DOCS = HERE / "docs"
LIGHT_BG, DARK_BG = "#f6f1e9", "#110f1a"   # match --bg in game.py
ICONS = {                                   # file: (size, full-bleed?)
    "icons/icon-192.png": (192, False),
    "icons/icon-512.png": (512, False),
    "icons/maskable-512.png": (512, True),   # Android crops this to its own shape, so no rounded corners
    "icons/apple-touch-icon.png": (180, True),  # iOS rounds the corners itself and hates transparency
}

PWA_HEAD = f"""<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" href="icons/icon-192.png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<meta name="theme-color" content="{LIGHT_BG}" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="{DARK_BG}" media="(prefers-color-scheme: dark)">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Lizard Leap">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<script>
  // offline support: sw.js keeps a copy of the game so the installed app opens without internet
  if ("serviceWorker" in navigator) addEventListener("load", () => navigator.serviceWorker.register("sw.js").catch(() => {{}}));
</script>"""

# Network first so players always get the newest version when online; the cache is the offline fallback.
SERVICE_WORKER = """// Lizard Leap offline support (generated by build.py - edit it there, not here)
const CACHE = "lizard-leap-%(version)s";
const FILES = %(files)s;

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("lizard-leap-") && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener("fetch", e => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(
    fetch(e.request)
      .then(res => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); }
        return res;
      })
      .catch(() => caches.match(e.request, { ignoreSearch: true })
        .then(hit => hit || caches.match("./index.html")))
  );
});
"""


def build_pwa(page: str):
    from PIL import Image

    write(DOCS / "index.html", page.replace(PWA_MARKER, PWA_HEAD))

    for name, (size, full_bleed) in ICONS.items():
        out = DOCS / name
        out.parent.mkdir(parents=True, exist_ok=True)
        draw_icon(full_bleed).resize((size, size), Image.NEAREST).save(out)
        print(f"Built {out.relative_to(HERE)}")

    manifest = {
        "id": "./",
        "name": "Lizard Leap",
        "short_name": "Lizard Leap",
        "description": "A tiny pixel-art desert runner: jump rocks, duck birds, eat berries.",
        "start_url": "./",
        "scope": "./",
        "display": "fullscreen",
        "orientation": "landscape",
        "background_color": LIGHT_BG,
        "theme_color": LIGHT_BG,
        "icons": [
            {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": "icons/maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
        ],
    }
    write(DOCS / "manifest.webmanifest", json.dumps(manifest, indent=2) + "\n")

    # The cache name changes whenever the site does, which tells installed apps to update.
    files = ["./", "index.html", "manifest.webmanifest", *ICONS]
    digest = hashlib.sha256()
    for f in files[1:]:
        digest.update((DOCS / f).read_bytes())
    write(DOCS / "sw.js", SERVICE_WORKER % {"version": digest.hexdigest()[:10], "files": json.dumps(files)})


# The standing lizard from game.py, drawn on a little patch of desert for the app icon.
ICON_SPRITE = [
    "...........GGG..",
    "..........GGGGEG",
    "....GDGDGDGGGGGG",
    "..GGGGGGGGGGGG..",
    "GG.LLLLLLLLL....",
    "....G.....G.....",
    "...G.......G....",
]
ICON_COLORS = {"G": "#5dae3c", "D": "#35751f", "L": "#cfe57e", "E": "#161616"}


def draw_icon(full_bleed: bool = False):
    """The icon at 1 image pixel per sprite pixel; callers scale it up with NEAREST to stay crisp.

    full_bleed=False: rounded square with an outline and transparent corners (desktop, browser tab).
    full_bleed=True:  edge-to-edge scene with the lizard inside the middle 80%, for phones
                      that cut the icon into their own shape (circle, squircle, ...).
    """
    from PIL import Image, ImageColor, ImageDraw

    grid, horizon, left = (24, 16, 4) if full_bleed else (20, 14, 2)
    img = Image.new("RGBA", (grid, grid), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, grid - 1, horizon - 1], fill="#7cc4e8")          # sky
    d.rectangle([0, horizon, grid - 1, grid - 1], fill="#e8b877")       # sand
    if not full_bleed:
        mask = Image.new("L", (grid, grid), 0)                           # trim to a rounded square
        ImageDraw.Draw(mask).rounded_rectangle([0, 0, grid - 1, grid - 1], radius=4, fill=255)
        img.putalpha(mask)
        d.rounded_rectangle([0, 0, grid - 1, grid - 1], radius=4, outline="#2b2118")
    top = horizon - len(ICON_SPRITE)
    for r, row in enumerate(ICON_SPRITE):
        for c, ch in enumerate(row):
            if ch != ".":
                img.putpixel((left + c, top + r), ImageColor.getrgb(ICON_COLORS[ch]))
    return img


def make_icon() -> Path:
    from PIL import Image

    WORK.mkdir(exist_ok=True)
    out = WORK / "icon.ico"
    draw_icon().resize((256, 256), Image.NEAREST).save(
        out, sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    return out


def build_exe():
    icon = make_icon()
    cmd = [
        sys.executable, "-m", "PyInstaller", str(HERE / "game.py"),
        "--name", "LizardLeap",
        "--onefile",                         # a single .exe to hand to people
        "--icon", str(icon.resolve()),
        "--collect-submodules", "uvicorn",   # uvicorn loads parts of itself by name at runtime
        "--distpath", str(DIST),
        "--workpath", str(WORK / "pyinstaller"),
        "--specpath", str(WORK),
        "--noconfirm", "--clean", "--log-level", "WARN",
    ]
    print("Building LizardLeap.exe (takes a minute)...")
    subprocess.run(cmd, check=True, cwd=HERE)
    out = DIST / "LizardLeap.exe"
    print(f"Built {out.relative_to(HERE)} ({out.stat().st_size // (1024 * 1024)} MB)")


TARGETS = {"html": build_html, "exe": build_exe}

if __name__ == "__main__":
    wanted = sys.argv[1:] or list(TARGETS)
    for name in wanted:
        if name not in TARGETS:
            sys.exit(f"Unknown target '{name}'. Choose from: {', '.join(TARGETS)}")
        TARGETS[name]()
